name             'percona-multi'
maintainer       'Rackspace Hosting, Inc.'
maintainer_email 'rackspace-cookbooks@rackspace.com'
license          'Apache 2.0'
description      'Provides Percona master/slave replication services'
version          '1.0.0'

depends 'build-essential'
depends 'percona'
depends 'apt'
depends 'yum'
depends 'mysql2_chef_gem'
